= Sample Spring Boot Application

IMPORTANT: This example application requires Java 8 JDK or greater and Maven 3.3.x or greater.


== Running the Example Application on a Single-node OpenShift Cluster
If you have a single-node OpenShift cluster, such as Minishift or Red Hat Container Development Kit, installed and running, you can also deploy your example application there. A single-node OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

To deploy your example application to a running single-node OpenShift cluster:
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer

$ oc new-project MY_PROJECT_NAME

$ mvn clean fabric8:deploy -Popenshift
----


== Interacting with the Example Application on a Single-node OpenShift Cluster

To interact with your example application while it is running on a Single-node OpenShift Cluster, you first need to obtain its URL:

[source,bash,options="nowrap",subs="attributes+"]
----
$ oc get route MY_APP_NAME -o jsonpath={$.spec.host}

MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME
----


You can use the form at your application's URL or you can use the `curl` command:

.List all entries in the database
[source,bash,options="nowrap",subs="attributes+"]
----
$ curl http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/fruits

[ {
  "id" : 1,
  "name" : "Cherry",
}, {
  "id" : 2,
  "name" : "Apple",
}, {
  "id" : 3,
  "name" : "Banana",
} ]
----

.Retrieve an entry with a specific ID
[source,bash,options="nowrap",subs="attributes+"]
----
curl http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/fruits/3

{
  "id" : 3,
  "name" : "Banana",
}
----


.Create a new entry:
[source,bash,options="nowrap",subs="attributes+"]
----
curl -H "Content-Type: application/json" -X POST -d '{"name":"pear"}'  http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/fruits

{
  "id" : 4,
  "name" : "pear",
}
----


.Update an Entry
[source,bash,options="nowrap",subs="attributes+"]
----
curl -H "Content-Type: application/json" -X PUT -d '{"name":"pineapple"}'  http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/fruits/1

{
  "id" : 1,
  "name" : "pineapple",
}
----


.Delete an Entry:
[source,bash,options="nowrap",subs="attributes+"]
----
curl -X DELETE http://MY_APP_NAME-MY_PROJECT_NAME.LOCAL_OPENSHIFT_HOSTNAME/api/fruits/1
----

NOTE: If you receive an HTTP Error code `503` as a response after executing these commands, it means that the application is not ready yet.

== More Information
You can learn more about this example application and rest of the Spring Boot runtime in the link:https://access.redhat.com/documentation/en-us/red_hat_support_for_spring_boot/[Spring Boot Runtime Guide].

NOTE: Run the set of integration tests included with this example application using `mvn clean verify -Popenshift,openshift-it`.
